config/routes.rb
Rails.application.routes.draw do
  root              'static_pages#home'

  get 'help'    =>  'static_pages#help'
  get 'about'   =>  'static_pages#about'
  get 'contact' =>  'static_pages#contact'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def full_title(page_title = '')
    base_title = "Skracarka linków \"Slim Link \""
    if page_title.empty?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Twórcą skracarki 'Slim Link' jest Dominik Malik. Wszelkie prawa zastrzeżone.
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Kontakt", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "SLIM-LINK", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",   root_path %></li>
        <li><%= link_to "Help",   help_path %></li>
        <li><%= link_to "Log in", '#' %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | Skracarka linków "Slim Link"</title>
    <%= stylesheet_link_tag    'application', media: 'all',
                               'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %> 
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>O mnie</h1>
<p>Na razie nie ma po co tego uzupełniać</p>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<h1>Kontakt</h1>
<p>
  The <a href="http://www.railstutorial.org/"><em>Ruby on Rails
  Tutorial</em></a> is a
  <a href="http://www.railstutorial.org/book">book</a> and
  <a href="http://screencasts.railstutorial.org/">screencast series</a>
  to teach web development with
  <a href="http://rubyonrails.org/">Ruby on Rails</a>.
  This is the sample application for the tutorial.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Pomoc</h1>
<p>W sumie nie wiem po co tu pomoc bo nic w tym trudnego :)</p>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<div class="center jumbotron">
  <h1>"Slim Link" - najlepsza skracarka adresów !</h1>

  <%= link_to "Wypróbuj teraz!", '#', class: "btn btn-lg btn-primary" %>

  <p><strong>O Skracarce "Slim Link"</strong></p>
  
  <p>
   Serwis "Slim link" powstał w 2014 roku. Jest to projekt stworzony oprogramowaniu Ruby on Rails.
  </p>
  <p>
   Projekt skracarki do adresów URL ma charakter w pełni <strong>niekomercyjny</strong>. 
   Służy do <strong>skracania</strong> zbyt długich adresów www.
   </p>
 </div>